# Generated by Django 5.1.4 on 2024-12-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
        migrations.AddField(
            model_name="wishlist",
            name="products",
            field=models.ManyToManyField(
                related_name="wishlists", to="products.product"
            ),
        ),
    ]
